(function () {
  const config = window.VL_CMS_CONFIG;
  if (!config || !window.supabase) return;
  const client = window.supabase.createClient(config.url, config.key);
  const loginPanel = document.querySelector('#login-panel');
  const cmsPanel = document.querySelector('#cms-panel');
  const loginForm = document.querySelector('#login-form');
  const loginStatus = document.querySelector('#login-status');
  const signOut = document.querySelector('#sign-out');
  const form = document.querySelector('#content-form');
  const list = document.querySelector('#content-list');
  const status = document.querySelector('#form-status');
  const save = document.querySelector('#save-button');
  const cancel = document.querySelector('#cancel-edit');
  const editor = document.querySelector('#editor-title');
  let records = [];

  const localDate = (value) => { const d = value ? new Date(value) : new Date(); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0,16); };
  const readablePlacement = (value) => ({homepage:'Homepage',lab:'The Lab',shop:'The Collective',etsy:'Etsy Drops',essentials:'The Essentials',creator:'Creator Mode',travel:'Travel & Lifestyle',updates:'Updates'})[value] || value;
  const schedule = (item) => { if (item.status === 'Draft') return 'Private draft'; const d = new Date(item.publish_at).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}); return item.status === 'Scheduled' || new Date(item.publish_at) > new Date() ? `Scheduled · ${d}` : `Live since ${d}`; };

  function reset() { form.reset(); form.elements.id.value=''; form.elements.placement.value='homepage'; form.elements.status.value='Draft'; form.elements.publish_at.value=localDate(); form.elements.sort_order.value='0'; editor.textContent='Create an update'; save.textContent='Save update'; cancel.classList.add('hidden'); status.textContent=''; }
  function edit(item) { form.elements.id.value=item.id; ['placement','status','eyebrow','title','body','cta_label','cta_url','image_url','sort_order'].forEach((key)=>form.elements[key].value=item[key] ?? ''); form.elements.publish_at.value=localDate(item.publish_at); form.elements.expires_at.value=item.expires_at?localDate(item.expires_at):''; editor.textContent='Edit update'; save.textContent='Save changes'; cancel.classList.remove('hidden'); window.scrollTo({top:0,behavior:'smooth'}); }
  function render() { list.replaceChildren(); if (!records.length) { list.textContent='No CMS items yet. Create the first one on the left.'; return; } records.forEach((item)=>{ const card=document.createElement('article'); card.className=`item ${item.status==='Published'?'live':item.status==='Scheduled'?'scheduled':''}`; const copy=document.createElement('div'); const tag=document.createElement('span'); tag.className='tag'; tag.textContent=(item.eyebrow||readablePlacement(item.placement)).toUpperCase(); const title=document.createElement('h3'); title.textContent=item.title; const body=document.createElement('p'); body.textContent=item.body||'No supporting copy.'; const meta=document.createElement('div'); meta.className='meta'; [item.status.toUpperCase(),readablePlacement(item.placement).toUpperCase(),schedule(item)].forEach((text)=>{const pill=document.createElement('span');pill.textContent=text;meta.append(pill);}); copy.append(tag,title,body,meta); const actions=document.createElement('div'); actions.className='actions'; const editBtn=document.createElement('button');editBtn.textContent='EDIT';editBtn.onclick=()=>edit(item);const liveBtn=document.createElement('button');liveBtn.textContent=item.status==='Published'?'UNPUBLISH':'PUBLISH NOW';liveBtn.onclick=async()=>{const {error}=await client.from(config.table).update(item.status==='Published'?{status:'Draft'}:{status:'Published',publish_at:new Date().toISOString()}).eq('id',item.id);if(error)status.textContent='That change was not allowed. Confirm this account is an approved CMS administrator.';await refresh();};const deleteBtn=document.createElement('button');deleteBtn.textContent='DELETE';deleteBtn.onclick=async()=>{if(!confirm(`Delete “${item.title}”?`))return;const {error}=await client.from(config.table).delete().eq('id',item.id);if(error)status.textContent='That item could not be deleted.';if(form.elements.id.value===item.id)reset();await refresh();};actions.append(editBtn,liveBtn,deleteBtn);card.append(copy,actions);list.append(card); }); }
  async function refresh() { list.textContent='Loading…'; const {data,error}=await client.from(config.table).select('*').eq('brand',config.brand).order('updated_at',{ascending:false}).limit(100); if(error){list.textContent='CMS setup is not active for this account yet. Run the VL Body Lab CMS migration once in Supabase.';return;} records=data||[];render(); }
  async function showApp() { loginPanel.classList.add('hidden'); cmsPanel.classList.remove('hidden'); signOut.classList.remove('hidden'); reset(); await refresh(); }
  loginForm.addEventListener('submit',async(e)=>{e.preventDefault();loginStatus.textContent='Signing in…';const {error}=await client.auth.signInWithPassword({email:loginForm.elements.email.value.trim(),password:loginForm.elements.password.value});loginStatus.textContent=error?'Sign-in failed. Check the email and password.':'';if(!error)showApp();});
  signOut.addEventListener('click',async()=>{await client.auth.signOut();location.reload();}); cancel.addEventListener('click',reset);document.querySelector('#refresh').addEventListener('click',refresh);
  form.addEventListener('submit',async(e)=>{e.preventDefault();const f=form.elements,publishAt=new Date(f.publish_at.value),expiresAt=f.expires_at.value?new Date(f.expires_at.value):null;if(Number.isNaN(publishAt.getTime())||(expiresAt&&expiresAt<=publishAt)){status.textContent='The expiry must be later than the publish time.';return;}save.disabled=true;const payload={brand:config.brand,placement:f.placement.value,status:f.status.value,eyebrow:f.eyebrow.value.trim()||null,title:f.title.value.trim(),body:f.body.value.trim()||null,cta_label:f.cta_label.value.trim()||null,cta_url:f.cta_url.value.trim()||null,image_url:f.image_url.value.trim()||null,publish_at:publishAt.toISOString(),expires_at:expiresAt?expiresAt.toISOString():null,sort_order:Number(f.sort_order.value)||0};const query=f.id.value?client.from(config.table).update(payload).eq('id',f.id.value):client.from(config.table).insert(payload);const {error}=await query;save.disabled=false;if(error){status.textContent='The update could not be saved. Confirm the CMS migration is run and this account is approved as an administrator.';return;}status.textContent=payload.status==='Published'?'Published. The site will update automatically.':payload.status==='Scheduled'?'Scheduled. It will go live automatically.':'Saved as a private draft.';reset();await refresh();});
  client.auth.getSession().then(({data})=>{if(data.session)showApp();});
}());
